### ISSUE TITLE
Video random access

### ISSUE THREAD

**Issue by idobrt** [olivierayache/xuggle-xuggler#10]
thanks for this fork man. I begin  to process video on hadoop with xuggler dependencies (HVPI). I need to make somes adjusts because HVPI don't support random access. To process a video on hadoop i will need to read a file from a random position on the video. Do you know some way to read a video data stream (random access)?

**Comment by olivierayache** [comment]
Xuggler provide API to read video with an InputStream through
IContainer.open method. Is this what you need?

**Comment by idobrt** [comment]
I will try to explain better. Sorry my english is not good.
The HVPI use this. But I want, for example, read just a small video chunk around 128 MB in any position. For example I will read the first 128MB of a video file, save this position and start to read from this position. I will process these chunks in a cluster machine. But if I break the file in a wrong position i will lose the data. The HVPI use container.readNextPacket(packet) to extract the video frames but its supose the video file is a entire file. If my video file is bigger than 128MB (a hadoop default block size) it will be so slowler because the container.readNextPacket(packet) will read the packt until the file finish. But if I could cut the bigger video in the rigth position I will can process it around lot of machines.

**Comment by olivierayache** [comment]
I don't know if it fet your needs but you could use seekKeyFrame method from IContainer to seek at a given timestamp
