### ISSUE TITLE
Windows 32-bit

### ISSUE THREAD

**Issue by ozgunu** [olivierayache/xuggle-xuggler#26]
Hello, is there a jar file compiled to support both Windows 32 bit and Windows 64 bit? The project I am working on requires both and so far I could not manage to compile it from source. I checked your Cloudsmith artifactory, saw the xuggle-xuggler-server-all.jar but it only supports Windows 64 bit. Thanks!

**Comment by olivierayache** [comment]
I will try to deploy a 32 bit Windows jar as soon as possible on Cloudsmith

**Comment by ozgunu** [comment]
Thank you, will be looking forward to it.

**Comment by olivierayache** [comment]
Hi @ozgunu I've just uploaded a windows 32/64 bits jar here https://cloudsmith.io/~olivier-ayache/repos/xuggler/packages/detail/maven/xuggle-xuggler-windows-all

**Comment by ozgunu** [comment]
Thanks a lot @olivierayache
