### ISSUE TITLE
Support for h264

### ISSUE THREAD

**Issue by wittenbe** [olivierayache/xuggle-xuggler#5]
Hey, thanks for this fork. I'm not terribly familiar with xuggler, but is there a way for me to enable h264/libx264 for encoding?

**Comment by wittenbe** [comment]
I just noticed libx264 is only available in a LGPL build, gotta get building then.

**Comment by olivierayache** [comment]
Yes to enable libx264 you have to build a GPL version of Xuggler. Default build will do this. Perhaps I could put a GPL build in branch repo too.

**Comment by wittenbe** [comment]
I tried the master branch. After some struggle with warnings-as-errors (had to set VS_WARN_ISERROR to false), I managed to get a build done, but it's not quite working:

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5d9420fc15, pid=11512, tid=140039904970496
#
# JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libc.so.6+0x160c15]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# hs_err_pid11512.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

log file: https://gist.github.com/wittenbe/352193561aa129cd1665

I'm on Ubuntu 14.04 with gcc/g++ 4.9.2 and java 1.8. Any idea what's wrong?

Edit: looks like you build yours with java 1.7. Guess it can't hurt to try the same.
Edit 2: unsurprisingly, that did nothing.

**Comment by olivierayache** [comment]
I will put GPL build from branch 2.6.3 in repo if you want.

**Comment by wittenbe** [comment]
That'd be great.

**Comment by olivierayache** [comment]
Repo now contains GPL version based on ffmpeg 2.6.3 with X264 coder.

**Comment by wittenbe** [comment]
Oh man, this is amazing. I'm getting some massive speed ups compared to the main/old xuggler. Thanks a lot.
By the way, the problem above only appeared when I tried to encode with libx264, but it doesn't appear in your build, so whatever.
